### ISSUE TITLE
Ground error on PCB

### ISSUE THREAD

**Issue by svdrummer** [RalphBacon/Universal-Timer-ATMega328PB-74HC165-Shift-Register#1]
When I click on the export Gerber file button, the self check system finds a ground error. I am new to EasyEDA, so it may be a simple fix.

**Comment by RalphBacon** [comment]
How odd, I get zero errors on my local system, but I shall check it out more thoroughly soon. Thanks for the heads up.

**Comment by svdrummer** [comment]
I will run it again and write down the NET name.
